//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formularios.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Formularios.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_airplane_aircraft_clip_art_airplane_png_clipart_5a7a209ef2d7c1_6834792815179531829947 {
            get {
                object obj = ResourceManager.GetObject("kisspng-airplane-aircraft-clip-art-airplane-png-clipart-5a7a209ef2d7c1.6834792815" +
                        "179531829947", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_airplane_aircraft_computer_icons_takeoff_airplane_icon_vector_5ab055f8246dd1_5981564015215057841492 {
            get {
                object obj = ResourceManager.GetObject("kisspng-airplane-aircraft-computer-icons-takeoff-airplane-icon-vector-5ab055f8246" +
                        "dd1.5981564015215057841492", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_airplane_icon_a5_computer_icons_flight_airplane_5ad24caf248134_0904397415237316311495 {
            get {
                object obj = ResourceManager.GetObject("kisspng-airplane-icon-a5-computer-icons-flight-airplane-5ad24caf248134.0904397415" +
                        "237316311495", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_bavaria_fluggesellschaft_airline_logo_clip_art_sch_5c7b1b23953315_0919425015515717476111 {
            get {
                object obj = ResourceManager.GetObject("kisspng-bavaria-fluggesellschaft-airline-logo-clip-art-sch-5c7b1b23953315.0919425" +
                        "015515717476111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_house_home_desktop_wallpaper_clip_a_home_icon_5acbedfca33fc9_8943084515233141726687 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-house-home-desktop-wallpaper-clip-a-home-icon-5acbedfca33f" +
                        "c9.8943084515233141726687", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_profile_clip_art_person_icon_user_person_man_icon_5ab04a2c1dfa10_0741935615215027641228 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-profile-clip-art-person-icon-user-person-man-icon-5ab" +
                        "04a2c1dfa10.0741935615215027641228", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_leaning_tower_of_pisa_flight_airplane_airline_tick_vector_airplane_tickets_5a96943d86d3c5_4497741515198177895523 {
            get {
                object obj = ResourceManager.GetObject("kisspng-leaning-tower-of-pisa-flight-airplane-airline-tick-vector-airplane-ticket" +
                        "s-5a96943d86d3c5.4497741515198177895523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
